version: 0.2

phases:
  pre_build:
    commands:
      - rm -rf *.zip
      - rm -rf *.pyc __pycache__/
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt -t .
  build:
    commands:
      - zip -r lambda_package.zip *.py *
artifacts:
  files:
    - lambda_package.zip