# Deploy Python project to Azure Function App with Remote Build
# Docs: https://github.com/Azure/functions-action
#       https://learn.microsoft.com/azure/azure-functions/functions-deployment-technologies

name: Build and deploy Python project to Azure Function App - DB-Populate-Linux-Premium

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'   # Your function project root
  PYTHON_VERSION: '3.11'               # Let Oryx pick the latest patch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Functions (Remote Build)
        uses: Azure/functions-action@v1
        with:
          app-name: 'DB-Populate-Linux-Premium'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          remote-build: true
